server:
  port: 8080
api:
  url: /api/v1/
token:
  signing:
    key: EBE23F1FD75A89A9355F1A81D194EUEISJDLJg23455jjuriu43387kjksfgjlkiuRDDRTGFDXVRXFBERJLIUMLSIhhYLCISL
spring:
  profiles:
    active: dev
  application:
    name: MedTracker
  jpa:
    generate-ddl: false
    show-sql: true
  sql:
    init:
      mode: always
      continue-on-error: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: medtrackerdemo2025@gmail.com
    password: jusx zvql rqgp cbja
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
initialData:
  loadFromFile: false
website:
  origin: ''
  localOrigin: ''




